Impl cpu.h
Raphine/Raph_Library pull request #78
Opened 2016-09-09 17:55 UTC by hikalium

2016-09-09 17:59 UTC, liva commented on rlib/cpu.h
> +  enum CpuPurposes {
特段の理由がない（intへ代入したいなど）場合、c++11のenum classの方が型チェックが強力なので、使いましょう。

2016-09-09 18:01 UTC, liva commented on rlib/cpu.h
> +	kCpuPurposesLen
LenよりはNumじゃないでしょうか

2016-09-09 18:01 UTC, liva commented on rlib/cpu.h
> +  int RetainCpuIdForPurpose(CpuPurposes p) override {
未割当のcpuを全部GeneralPurposeに割り当てるメソッドがあると良いと思います。

2016-09-10 04:02 UTC, levelfour commented on rlib/cpu.h
> +	kLowPriority,
インデントはスペースで！

2016-09-10 04:10 UTC, levelfour commented on rlib/cpu.h
> +  const int kCpuIdNotFound = -1;
命名について、`CpuId`か`Id`かどちらかに統一したほうがいいかと。僕は`CpuCtrl`が返すIDなんだからわざわざ`CpuId`と明示しなくてもいいかなと思ったんですが、異論あったら変えてもらっても構わないです。

2016-09-10 04:18 UTC, levelfour commented on rlib/cpu.h
> +      // boot processor is always assigned to kLowPriority
このコメントは65行目に対するコメント？（だとしたら前の行にコメントを置くのが適切だと思います）

2016-09-10 04:20 UTC, levelfour commented on rlib/cpu.h
> +  const int kCpuIdBootProcessor = 0;
`int`は`int32_t`でお願いします（まあ元々僕が間違えた気がするが…）

2016-09-10 04:22 UTC, levelfour commented on rlib/cpu.h
> +    return 0;
ここで`0`を返すのは期待されている挙動？（`kCpuIdBootProcessor = 0`）
想定挙動なら`kCpuIdBootProcessor`と書くべきだけど、たぶん`kCpuIdNotFound`の間違いかな？

2016-09-10 04:25 UTC, levelfour commented on rlib/cpu.h
> +    for(i = 0; i < len; i++){
これはC++です！！！(`for(int32_t i = 0; ... )`)
ついでに、`len`はどうせ使わないならfor文の中で直接`GetHowManyCpus()`を呼んでしまったほうがいいと思う

2016-09-10 04:27 UTC, levelfour commented on rlib/cpu.h
> +    for(i = 0; i < len; i++){
C++！！！

2016-09-10 04:29 UTC, levelfour commented on rlib/cpu.h
> +  void ReleaseCpuId(int cpuid) override {
ワンクッション挟んで呼ぶだけの`_ReleaseCpuId`を定義する理由は？

2016-09-10 05:57 UTC, liva commented on rlib/cpu.h
> +  const int kCpuIdBootProcessor = 0;
googleのコーディング規約では、単純な整数はintで良いとなっているので、これはこのままで良いかと。

2016-09-10 05:58 UTC, liva commented on rlib/cpu.h
> +    for(i = 0; i < len; i++){
int32_tでなくてintでおｋ。（上のコメント参照）

2016-09-17 14:46 UTC, hikalium commented on rlib/cpu.h
> +  enum CpuPurposes {
fixed

2016-09-17 14:46 UTC, hikalium commented on rlib/cpu.h
> +	kCpuPurposesLen
fixed

2016-09-17 14:47 UTC, hikalium commented on rlib/cpu.h
> +  int RetainCpuIdForPurpose(CpuPurposes p) override {
どういったときにそのメソッドは使うのですか？使い時がいまいちわからないです…。

2016-09-17 14:51 UTC, hikalium commented on rlib/cpu.h
> +	kLowPriority,
fixed

2016-09-17 14:52 UTC, hikalium commented on rlib/cpu.h
> +  const int kCpuIdNotFound = -1;
私はCpuIdにしたい（APIC IDと紛らわしいというのがその最大の理由です）ので、既存のメソッドについてもCpuIdに変更します。

2016-09-17 15:01 UTC, hikalium commented on rlib/cpu.h
> +  const int kCpuIdNotFound = -1;
fixed

2016-09-17 15:01 UTC, hikalium commented on rlib/cpu.h
> +      // boot processor is always assigned to kLowPriority
fixed

2016-09-17 15:05 UTC, hikalium commented on rlib/cpu.h
> +    return 0;
0を返すのは想定された挙動です。
（この関数は常に、有効なCpuIdのいずれかを返し、現在の実装では、割り当てられるCpuがない場合には、BootProcessorに割り当てるということになっています。したがってkCpuIdNotFoundを返すことはありません。）
kCpuIdBootProcessorと書くべきだという指摘はその通りなので、修正いたします。

2016-09-17 15:06 UTC, hikalium commented on rlib/cpu.h
> +    return 0;
fixed

2016-09-17 15:08 UTC, hikalium commented on rlib/cpu.h
> +    for(i = 0; i < len; i++){
変数宣言をforの初期化式で書いたほうが良いというのは、変数のスコープを制限するためでしょうか。
lenに関しては、GetHowManyCpus()をループごとに呼ぶのは非効率的なのでこのような実装にしていますが、いかがでしょうか。

2016-09-17 15:14 UTC, liva commented on rlib/cpu.h
> +  int RetainCpuIdForPurpose(CpuPurposes p) override {
初期化が全て終わった後、残りの全てのcpuでアプリケーションプロセスを走らせられるようにしたいのです。

2016-09-17 15:17 UTC, liva commented on rlib/cpu.h
> +  const int kCpuIdNotFound = -1;
APIC IDと紛らわしいかなぁという気が。アクセスする時ってCpuCtrl::GetId()とか、ApicCtrl::GetId()とかするわけで、むしろCpuCtrl::GetCpuId()の方が冗長かと思いました。

2016-09-17 15:20 UTC, liva commented on rlib/cpu.h
> +    for(i = 0; i < len; i++){
たぶんfor (int i = 0; i < len; i++)と、int len = GetHowManyCpus();って事でしょうね。変数のスコープを制限する、という確固たる目的のためではなくて純粋にc++のコードって使いたくなった時に宣言するのが慣習になっているから、という事かと。（僕も気になったけど、悩んだ末にコメントを残さなかったのは、結局個人の好き嫌いの問題になってしまうかなぁと思ったので）
ただまあ、Cっぽく書くのは気持ち悪くはありますね。

2016-09-17 15:48 UTC, hikalium commented
conflict resolved.

2016-09-17 15:56 UTC, liva commented
インターフェースが変わったので、副作用がある事をp-rに記載してください。
こんな感じで、タイトルに"contains side effects"をつけるのと、expected impact（副作用）を記載してください。
https://github.com/Raphine/Raph_Library/issues/11

2016-09-17 16:10 UTC, hikalium commented
未割り当てのCPUをすべてGeneralPurposeに割り当てるメソッドの件について、これはユーザーランドから呼び出す可能性があるでしょうか？（CpuCtrlInterfaceに追加する必要があるか、ということ）
もしユーザーランドから呼び出さないならば、CpuCtrlInterfaceに追加するべきではないと思うのですが、そうするとkernel側で使うときにキャストしなければいけない（CpuCtrlInterface型として保持しているから）と思うのですが、どうしましょうか。

2016-09-17 16:14 UTC, liva commented
確かに、ユーザーランド側で必要な関数ではないですが、インターフェースとしてはあっても問題ないと思います。
ユーザーランドでは空実装とかで良いのでは。

2016-09-17 16:40 UTC, hikalium commented
waiting for review.

2016-09-22 13:10 UTC, liva commented
現状は問題なさげ

2016-10-03 00:13 UTC, liva approved these changes

2016-10-03 00:13 UTC, liva commented on rlib/cpu.h
> +  private:
privateとpublicの場所逆ですね→コーディング規約

2016-10-03 00:13 UTC, liva commented on rlib/cpu.h
> +    void AssignCpusNotAssignedToGeneralPurpose(){
中括弧の前にスペース欲しいです→コーディング規約

2016-10-03 00:13 UTC, liva commented on rlib/functional.h
> +  _cpuid = cpuid.GetRawId();
_cpuidをCpuId型にすれば良いのでは？

2016-10-03 00:13 UTC, liva commented on rlib/polling.h
> +    _cpuid = cpuid.GetRawId();
同上

2016-10-03 00:13 UTC, liva commented on rlib/task.cc
> +  task->_cpuid = raw_cpu_id;
同上

2016-10-03 00:15 UTC, liva commented
間違えてapproveにしちゃったけど、Request changesです

2016-10-15 10:50 UTC, hikalium commented
waiting for reviewing

2016-10-15 15:31 UTC, liva commented on rlib/cpu.h
> +  private:
これ、修正されていない気がします

2016-10-15 15:32 UTC, liva requested changes
merge_#90というブランチを作ったので、そちらにp-rを出してもらえると有難いです

2016-10-15 16:26 UTC, merged